function broadcastTrial(opts, isRunning)
arguments (Input)
	opts struct
	isRunning logical = false
end

opts.broadcast.send(struct('task',opts.task,'name',opts.name,...
	'is_running',isRunning,...
	'trial_id',opts.trialN,...
	'rewards',opts.rewards,'correct_rate', opts.correctRate,...
	'result', opts.result, 'reaction_time', opts.reactionTime, ...
	'phase', opts.phase,...
	'correct_rate_last10', opts.correctRateRecent,...
	'start_time',opts.startTime,'end_time',opts.endTime,...
	'session_id',opts.alyxPath,'hostname',opts.hostname));

end
