function broadcastTrial(opts, isRunning)
arguments (Input)
	opts struct
	isRunning logical = false
end

opts.broadcast.send(struct(...
	'task',opts.task,...
	'name',opts.name,...
	'is_running',isRunning,...
	'session_id',opts.sessionID,...
	'loop_id',opts.loopN,...
	'trial_id',opts.trialN,...
	'rewards',opts.rewards,...
	'correct_rate', opts.correctRate,...
	'result', opts.result,...
	'phase', opts.phase,...
	'reaction_time', opts.pertrialtime, ...
	'correct_rate_last10', opts.correctRateRecent,...
	'start_time',opts.startTime,...
	'end_time',opts.endTime,...
	'hostname',opts.hostname));

end
