function empty_map = GenerateRandomMap_V13(dot_percentage)

%change from V10. Divided original 4 regions into smaller subregions. Each
%subregion (except the tunnel) contains 12- pellets
%Apart from tunnel, there are 15 subregions
%Therefore, the dot_percentage should be a 15*1 array
%subregion 1+6+7+8= original region 1;
%subregion 3+9+0= original region 3;
%subregion 2+a+b+c= original region 2;
%subregion 4+d+e+f= original region 4;

% global fruit_pos;
global startTile pstartTile;
global ghostNumber;
global scores;

scores =0;
ghostNumber = 2; %ZWY


global deadline; deadline = 900;

% ghostNumber = 2; %ZWY
dot_percentage = 0.8*ones(1,8);
empty_map = [ ...
    '____________________________' ...
    '____________________________' ...
    '____________________________' ...
    '||||||||||||||||||||||||||||' ...
    '|            ||            |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '|                          |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||    ||    ||      |' ...
    '|||||| ||||| || ||||| ||||||' ...
    '_____| ||||| || ||||| |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||--||| || |_____' ...
    '|||||| || |______| || ||||||' ...
    '          |______|          ' ...
    '|||||| || |______| || ||||||' ...
    '_____| || |||||||| || |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||||||| || |_____' ...
    '|||||| || |||||||| || ||||||' ...
    '|            ||            |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| ||||                |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||    ||    ||      |' ...
    '| |||||||||| || |||||||||| |' ...
    '| |||||||||| || |||||||||| |' ...
    '|                          |' ...
    '||||||||||||||||||||||||||||' ...
    '____________________________' ...
    '____________________________'];

startTile(:,1:2) = [14 15;18 19];
pstartTile = struct('x',14,'y',27);

dot_percentage = datasample(dot_percentage,length(dot_percentage),'Replace',false);%to randomize the regions that has dots

[region1, region2, region3, region4, region6, region7, region8, region9,tunnel] = DefineMapRegion;

% if length(region1) == length(region2)
    number_of_dots_per_region1 = floor(dot_percentage(1) * length(region1));
    number_of_dots_per_region2 = floor(dot_percentage(2) * length(region2));
    number_of_dots_per_region3 = floor(dot_percentage(3) * length(region3));
    number_of_dots_per_region4 = floor(dot_percentage(4) * length(region4));
    number_of_dots_per_region6 = floor(dot_percentage(5) * length(region6));
    number_of_dots_per_region7 = floor(dot_percentage(6) * length(region7));
    number_of_dots_per_region8 = floor(dot_percentage(7) * length(region8));
    number_of_dots_per_region9 = floor(dot_percentage(8) * length(region9));
%     number_of_dots_per_region0 = floor(dot_percentage(9) * length(region0));
%     number_of_dots_per_regiona = floor(dot_percentage(10) * length(regiona));
%     number_of_dots_per_regionb = floor(dot_percentage(11) * length(regionb));
%     number_of_dots_per_regionc = floor(dot_percentage(12) * length(regionc));
%     number_of_dots_per_regiond = floor(dot_percentage(13) * length(regiond));
%     number_of_dots_per_regione = floor(dot_percentage(14) * length(regione));
%     number_of_dots_per_regionf = floor(dot_percentage(15) * length(regionf));

    dots1 = datasample(region1,number_of_dots_per_region1,'Replace',false);
    dots2 = datasample(region2,number_of_dots_per_region2,'Replace',false);
    dots3 = datasample(region3,number_of_dots_per_region3,'Replace',false);
    dots4 = datasample(region4,number_of_dots_per_region4,'Replace',false);
    dots6 = datasample(region6,number_of_dots_per_region6,'Replace',false);
    dots7 = datasample(region7,number_of_dots_per_region7,'Replace',false);
    dots8 = datasample(region8,number_of_dots_per_region8,'Replace',false);
    dots9 = datasample(region9,number_of_dots_per_region9,'Replace',false);
%     dots0 = datasample(region0,number_of_dots_per_region0,'Replace',false);
%     dotsa = datasample(regiona,number_of_dots_per_regiona,'Replace',false);
%     dotsb = datasample(regionb,number_of_dots_per_regionb,'Replace',false);
%     dotsc = datasample(regionc,number_of_dots_per_regionc,'Replace',false);
%     dotsd = datasample(regiond,number_of_dots_per_regiond,'Replace',false);
%     dotse = datasample(regione,number_of_dots_per_regione,'Replace',false);
%     dotsf = datasample(regionf,number_of_dots_per_regionf,'Replace',false);
   
    dots = [dots1',dots2',dots3',dots4',dots6',dots7',dots8',dots9'];
    
%subregion 1+6+7+8= original region 1;
%subregion 3+9+0= original region 3; %region8 is actually for both orig 1&3
%subregion 2+a+b+c= original region 2;
%subregion 4+d+e+f= original region 4;

    enerarea1=[dots1',dots6'];
    enerarea2=[dots3',dots8'];
    enerarea3=[dots2',dots7'];
    enerarea4=[dots4',dots9'];
    
    if ~isempty(enerarea1)
         ener1 = datasample(enerarea1, 1);
    else
        ener1 =[];
    end
    if ~isempty(enerarea2)
         ener2 = datasample(enerarea2, 1);
    else
        ener2 =[];
    end
    if ~isempty(enerarea3)
         ener3 = datasample(enerarea3, 1);
    else
        ener3 =[];
    end
    if ~isempty(enerarea4)
        ener4 = datasample(enerarea4, 1);
    else
        ener4 =[];
    end
    eners = [ener1,ener2,ener3,ener4];
    
% elseif length(region1) == length(region3)
%     number_of_dots_per_region13 = floor(dot_percentage * length(region1));
%     number_of_dots_per_region24 = floor(dot_percentage * length(region2));
%     dots1 = datasample(region1,number_of_dots_per_region13,'Replace',false);
%     ener1 = datasample(dots1, 1);
%     dots2 = datasample(region2,number_of_dots_per_region24,'Replace',false);
%     ener2 = datasample(dots2, 1);
%     dots3 = datasample(region3,number_of_dots_per_region13,'Replace',false);
%     ener3 = datasample(dots3, 1);
%     dots4 = datasample(region4,number_of_dots_per_region24,'Replace',false);
%     ener4 = datasample(dots4, 1);
%     dots = [dots1,dots2,dots3,dots4];
%     eners = [ener1,ener2,ener3,ener4];
% else
%     error("something wrong with region defination")
% end
fruits = ['A' ; 'O' ; 'M' ; 'C' ; 'S'];

% dots in tunnel
dotsTunnel = datasample(tunnel,7,'Replace',false);
empty_map(dotsTunnel) = '.';

% Create map with dots, eners and fruit
% if  n <= 4
%     % have 2 regions
%      dots_region =datasample(dots,n,'Replace',false);
    dots_region =dots;
    energizer_region = eners(ismember(eners, dots_region));
%     dots_region = reshape(dots_region,1,[]);
    fruit_region = setdiff(dots_region, energizer_region);
    
    % fruit position --> noted to delete fruits
    fruit_pos = IndexToPosition(datasample(fruit_region,1));
    ener_pos = IndexToPosition(energizer_region);
    while abs(fruit_pos(1) - ener_pos(1)) + abs(fruit_pos(2) - ener_pos(3)) < 6 ...
            || abs(fruit_pos(1) - ener_pos(2)) + abs(fruit_pos(2) - ener_pos(4)) < 6 ...
            || abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) < 4 % far away from pacman start point
        fruit_pos = IndexToPosition(datasample(fruit_region,1));
    end
    fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));

if length(unique(dots_region)) ~= length(dots_region)
    error('the dots region has replicated one')
end

% creat map
% empty_map(setdiff([dots_region,energizer_region],fruit_region)) = '.';
empty_map(dots_region) = '.';
empty_map(energizer_region) = 'o';
empty_map(fruit_region) = datasample(fruits,1);

end

function [region1, region2, region3, region4, region6, region7, region8, region9, tunnel] = DefineMapRegion
empty_map = [ ...
    '____________________________' ...
    '____________________________' ...
    '____________________________' ...
    '||||||||||||||||||||||||||||' ...
    '|1111111     ||     3333333|' ...
    '|1|||| ||||| || ||||| ||||3|' ...
    '|1|||| |||||6||6||||| ||||3|' ...
    '|1|||| |||||6||6||||| ||||3|' ...
    '|           6666           |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||    ||    ||      |' ...
    '|||||| ||||| || ||||| ||||||' ...
    '_____| |||||8||8||||| |_____' ...
    '_____| ||8888888888|| |_____' ...
    '_____| || |||--||| || |_____' ...
    '|||||| || |______| || ||||||' ...
    '555555    |______|    555555' ...
    '|||||| || |______| || ||||||' ...
    '_____| || |||||||| || |_____' ...
    '_____| ||          || |_____' ...
    '_____| ||2||||||||4|| |_____' ...
    '|||||| ||2||||||||4|| ||||||' ...
    '|222222222   ||   444444444|' ...
    '|2|||| ||||| || ||||| ||||4|' ...
    '|2|||| ||||| || ||||| ||||4|' ...
    '| ||||                |||| |' ...
    '| |||| ||7||||||||9|| |||| |' ...
    '| |||| ||7||||||||9|| |||| |' ...
    '|      ||7777||9999||      |' ...
    '| ||||||||||7||9|||||||||| |' ...
    '| ||||||||||7||9|||||||||| |' ...
    '|          777999          |' ...
    '||||||||||||||||||||||||||||' ...
    '____________________________' ...
    '____________________________'];

region1 = find(empty_map == '1')';
region2 = find(empty_map == '2')';
region3 = find(empty_map == '3')';
region4 = find(empty_map == '4')';
region6 = find(empty_map == '6')';
region7 = find(empty_map == '7')';
region8 = find(empty_map == '8')';
region9 = find(empty_map == '9')';
tunnel = find(empty_map == '5')';
end