function empty_map = GenerateRandomMap_V10_sparse_dots
global startTile pstartTile;
global ghostNumber;
global fruit_pos
global deadline; deadline =  0.5*3600;
n = 4;
ghostNumber = 2; %ZWY
dot_percentage = [1,0.8,0.6,0.4];
dot_per = dot_percentage(randperm(4));

empty_map = [ ...
    '____________________________' ...
    '____________________________' ...
    '____________________________' ...
    '||||||||||||||||||||||||||||' ...
    '|            ||            |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '|                          |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||    ||    ||      |' ...
    '|||||| ||||| || ||||| ||||||' ...
    '_____| ||||| || ||||| |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||--||| || |_____' ...
    '|||||| || |______| || ||||||' ...
    '          |______|          ' ...
    '|||||| || |______| || ||||||' ...
    '_____| || |||||||| || |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||||||| || |_____' ...
    '|||||| || |||||||| || ||||||' ...
    '|            ||            |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| ||||                |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||    ||    ||      |' ...
    '| |||||||||| || |||||||||| |' ...
    '| |||||||||| || |||||||||| |' ...
    '|                          |' ...
    '||||||||||||||||||||||||||||' ...
    '____________________________' ...
    '____________________________'];

startTile(:,1:2) = [14 15;18 19];
pstartTile = struct('x',14,'y',27);
[region1, region2, region3, region4, eng] = DefineMapRegion;
dots1 = datasample(region1,floor(dot_per(1) * length(region1)),'Replace',false);
ener1 = datasample(eng,4,'Replace',false);
dots2 = datasample(region2,floor(dot_per(2) * length(region2)),'Replace',false);
%     ener2 = datasample(dots2, 1);
dots3 = datasample(region3,floor(dot_per(3) * length(region3)),'Replace',false);
%     ener3 = datasample(dots3, 1);
dots4 = datasample(region4,floor(dot_per(4) * length(region4)),'Replace',false);
%     ener4 = datasample(dots4, 1);
dots = [dots1.',dots2.',dots3.',dots4.'];
%     eners = [ener1,ener2,ener3,ener4];
eners = [ener1];
fruits = ['A' ; 'O' ; 'M' ; 'C' ; 'S'];

% dots in tunnel
% dotsTunnel = datasample(tunnel,7,'Replace',false);
% empty_map(dotsTunnel) = '.';


% Create map with dots, eners and fruit

if  n <= 4
    % have 2 regions
    dots_region = dots;
%     energizer_region = eners(ismember(eners, dots_region));
    energizer_region = eners;
    dots_region = reshape(dots_region,1,[]);
    fruit_region = setdiff(dots_region, energizer_region);
    
    % fruit position
    fruit_pos = IndexToPosition(datasample(fruit_region,1));
    ener_pos = IndexToPosition(energizer_region);
    while abs(fruit_pos(1) - ener_pos(1)) + abs(fruit_pos(2) - ener_pos(3)) < 6 ...
            || abs(fruit_pos(1) - ener_pos(2)) + abs(fruit_pos(2) - ener_pos(4)) < 6 ...
            || abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) < 4 % far away from pacman start point
        fruit_pos = IndexToPosition(datasample(fruit_region,1));
    end
    fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));
else
    error('dots region cannot larger than 3')
end

if length(unique(dots_region)) ~= length(dots_region)
    error('the dots region has replicated one')
end

% creat map
empty_map(setdiff([dots_region,energizer_region.'],fruit_region)) = '.';
empty_map(energizer_region) = 'o';
empty_map(fruit_region) = datasample(fruits,1);

end

function [region1, region2, region3, region4, eng] = DefineMapRegion
empty_map = [ ...
    '____________________________' ...
    '____________________________' ...
    '____________________________' ...
    '||||||||||||||||||||||||||||' ...
    '|11111111111 || 33333333333|' ...
    '| ||||1||||| || |||||3|||| |' ...
    '| ||||1||||| || |||||3|||| |' ...
    '| ||||1||||| || |||||3|||| |' ...
    '|                          |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||5   ||   5||      |' ...
    '|||||| ||||| || ||||| ||||||' ...
    '_____| ||||| || ||||| |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||--||| || |_____' ...
    '|||||| || |______| || ||||||' ...
    '         5|______|5         ' ...
    '|||||| || |______| || ||||||' ...
    '_____| || |||||||| || |_____' ...
    '_____| ||     5    || |_____' ...
    '_____| || |||||||| || |_____' ...
    '|||||| || |||||||| || ||||||' ...
    '|22222       ||       44444|' ...
    '|2|||| ||||| || ||||| ||||4|' ...
    '|2|||| ||||| || ||||| ||||4|' ...
    '| ||||                |||| |' ...
    '|2|||| || |||||||| || ||||4|' ...
    '|2|||| || |||||||| || ||||4|' ...
    '|22222 ||5   ||   5|| 44444|' ...
    '| |||||||||| || |||||||||| |' ...
    '| |||||||||| || |||||||||| |' ...
    '|            5             |' ...
    '||||||||||||||||||||||||||||' ...
    '____________________________' ...
    '____________________________'];

region1 = find(empty_map == '1')';
region2 = find(empty_map == '2')';
region3 = find(empty_map == '3')';
region4 = find(empty_map == '4')';
eng = find(empty_map == '5')';
end