function empty_map = GenerateRandomMap_easyV10(n,dot_percentage)
global fruit_pos;
% dot_percentage = 0.7;
empty_map = [ ...
    '____________________________' ...
    '____________________________' ...
    '____________________________' ...
    '||||||||||||||||||||||||||||' ...
    '|                          |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| |||| ||          || |||| |' ...
    '| |||| ||          || |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '|                          |' ...
    '|||||| |||||||||||||| ||||||' ...
    '_____| |||||||||||||| |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||--||| || |_____' ...
    '|||||| || |______| || ||||||' ...
    '       || |______| ||       ' ...
    '|||||| || |______| || ||||||' ...
    '_____| || |||||||| || |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||||||| || |_____' ...
    '|||||| || |||||||| || ||||||' ...
    '|      ||          ||      |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| ||||                |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| |||| ||          || |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '| |||| |||||||||||||| |||| |' ...
    '|                          |' ...
    '||||||||||||||||||||||||||||' ...
    '____________________________' ...
    '____________________________'];


load('map_easyv10_regions.mat');
number_of_dots_per_region13 = floor(dot_percentage * length(region1));
number_of_dots_per_region24 = floor(dot_percentage * length(region2));
region = zeros(1,2);
fruits = ['A' ; 'O' ; 'M' ; 'C' ; 'S'];
% Pick from region 1 and 3
x13 = rand(1,1);
if x13 < 0.5
    dots13 = datasample(region1,number_of_dots_per_region13,'Replace',false);
    ener13 = datasample(dots13, 1);
    region(1) = 1;
else
    dots13 = datasample(region3,number_of_dots_per_region13,'Replace',false);
    ener13 = datasample(dots13, 1);
    region(1) = 3;
end

% Pick from region 2 and 4
x24 = rand(1,1);
if x24 < 0.5
    dots24 = datasample(region2,number_of_dots_per_region24,'Replace',false);
    ener24 = datasample(dots24, 1);
    region(2) = 2;
else
    dots24 = datasample(region4,number_of_dots_per_region24,'Replace',false);
    ener24 = datasample(dots24, 1);
    region(2) = 4;
end

% dots in tunnel
dotsTunnel = datasample(tunnel,7,'Replace',false);
empty_map(dotsTunnel) = '.';

% Create map with dots, eners and fruit
if  n ==2
    % have 2 regions
    dots_region = [dots13',dots24'];
    energizer_region = [ener13, ener24];
    fruit_region = setdiff(dots_region, energizer_region);
    
    % fruit position
    fruit_pos = IndexToPosition(datasample(fruit_region,1));
    ener_pos = IndexToPosition(energizer_region);
    while abs(fruit_pos(1) - ener_pos(1)) + abs(fruit_pos(2) - ener_pos(3)) < 6 ...
            || abs(fruit_pos(1) - ener_pos(2)) + abs(fruit_pos(2) - ener_pos(4)) < 6 ...
            || abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) < 4 % far away from pacman start point
        fruit_pos = IndexToPosition(datasample(fruit_region,1));
    end
    fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));
    
elseif n == 3
    % add one more region
    more_region = rand(1,1);
    if more_region < 0.5
        dot_region = eval(sprintf('region%d',setdiff([1,3], region(1))));
        dotsmore = datasample(dot_region,number_of_dots_per_region13,'Replace',false);
        enermore = datasample(dotsmore, 1);
    else
        dot_region = eval(sprintf('region%d',setdiff([2,4], region(2))));
        dotsmore = datasample(dot_region,number_of_dots_per_region24,'Replace',false);
        enermore = datasample(dotsmore, 1);
    end
    dots_region = [dots13',dots24',dotsmore'];
    energizer_region = [ener13,ener24,enermore];
    fruit_region = setdiff(dots_region, energizer_region);
    % fruit position
    fruit_pos = IndexToPosition(datasample(fruit_region,1));
    ener_pos = IndexToPosition(energizer_region);
    while abs(fruit_pos(1) - ener_pos(1)) + abs(fruit_pos(2) - ener_pos(4)) < 6 ...
            || abs(fruit_pos(1) - ener_pos(2)) + abs(fruit_pos(2) - ener_pos(5)) < 6 ...
            || abs(fruit_pos(1) - ener_pos(3)) + abs(fruit_pos(2) - ener_pos(6)) < 6 ...
            || abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) < 4 % far away from pacman start point
        fruit_pos = IndexToPosition(datasample(fruit_region,1));
    end
    fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));
    
elseif n == 1
    % only 1 region
    more_region = rand(1,1);
    if more_region < 0.5
        dot_region = eval(sprintf('region%d',setdiff([1,3], region(1))));
        dotsmore = datasample(dot_region,number_of_dots_per_region13,'Replace',false);
        enermore = datasample(dotsmore, 1);
    else
        dot_region = eval(sprintf('region%d',setdiff([2,4], region(2))));
        dotsmore = datasample(dot_region,number_of_dots_per_region24,'Replace',false);
        enermore = datasample(dotsmore, 1);
    end
    dots_region = dotsmore';
    energizer_region = enermore;
    fruit_region = setdiff(dots_region, energizer_region);
    
    % fruit position
    fruit_pos = IndexToPosition(datasample(fruit_region,1));
    ener_pos = IndexToPosition(energizer_region);
    while abs(fruit_pos(1) - ener_pos(1)) + abs(fruit_pos(2) - ener_pos(2)) < 6 ...
            || abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) < 4 % far away from pacman start point
        fruit_pos = IndexToPosition(datasample(fruit_region,1));
    end
    fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));
    
else
    error('dots region cannot larger than 3')
end

if length(unique(dots_region)) ~= length(dots_region)
    error('the dots region has replicated one')
end

% creat map
empty_map(setdiff([dots_region,energizer_region],fruit_region)) = '.';
empty_map(energizer_region) = 'o';
empty_map(fruit_region) = datasample(fruits,1);


end

% empty_map = [ ...
%     '____________________________' ...
%     '____________________________' ...
%     '____________________________' ...
%     '||||||||||||||||||||||||||||' ...
%     '|111111111111||333333333333|' ...
%     '|1||||1|||||1||3|||||3||||3|' ...
%     '|1||||1|||||1||3|||||3||||3|' ...
%     '|1||||1|||||1||3|||||3||||3|' ...
%     '|11111111111113333333333333|' ...
%     '|1||||1||1||||||||3||3||||3|' ...
%     '|1||||1||1||||||||3||3||||3|' ...
%     '|111111||1111||3333||333333|' ...
%     '||||||1|||||1||3|||||3||||||' ...
%     '_____|1|||||1||3|||||3|_____' ...
%     '_____|1||          ||3|_____' ...
%     '_____|1|| |||--||| ||3|_____' ...
%     '||||||1|| |______| ||3||||||' ...
%     '5555555   |______|   5555555' ...
%     '||||||2|| |______| ||4||||||' ...
%     '_____|2|| |||||||| ||4|_____' ...
%     '_____|2||          ||4|_____' ...
%     '_____|2||2||||||||4||4|_____' ...
%     '||||||2||2||||||||4||4||||||' ...
%     '|222222222222||444444444444|' ...
%     '|2||||2|||||2||4|||||4||||4|' ...
%     '|2||||2|||||2||4|||||4||||4|' ...
%     '|2||||2222222244444444||||4|' ...
%     '|2||||2||2||||||||4||4||||4|' ...
%     '|2||||2||2||||||||4||4||||4|' ...
%     '|222222||2222||4444||444444|' ...
%     '|2||||||||||2||4||||||||||4|' ...
%     '|2||||||||||2||4||||||||||4|' ...
%     '|22222222222224444444444444|' ...
%     '||||||||||||||||||||||||||||' ...
%     '____________________________' ...
%     '____________________________'];
% for i = 1: 200
% fruit_pos = IndexToPosition(datasample(find(empty_map == '2'),1));
% while abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) >= 5 % far away from pacman start point
% fruit_pos = IndexToPosition(datasample(find(empty_map == '2'),1));
% fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));
% empty_map(fruit_region) = '0';
% end
% empty_map(fruit_region) = '2';
% end
% GetMapAtFrame(empty_map)
