function empty_map = GenerateRandomMap_V11
global fruit_pos;
n = 4;
dot_percentage = 0.4;
empty_map = [ ...
    '____________________________' ...
    '____________________________' ...
    '____________________________' ...
    '||||||||||||||||||||||||||||' ...
    '|            ||            |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '|                          |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||    ||    ||      |' ...
    '|||||| ||||| || ||||| ||||||' ...
    '_____| ||||| || ||||| |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||--||| || |_____' ...
    '|||||| || |______| || ||||||' ...
    '          |______|          ' ...
    '|||||| || |______| || ||||||' ...
    '_____| || |||||||| || |_____' ...
    '_____| ||          || |_____' ...
    '_____| || |||||||| || |_____' ...
    '|||||| || |||||||| || ||||||' ...
    '|            ||            |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| |||| ||||| || ||||| |||| |' ...
    '| ||||                |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '| |||| || |||||||| || |||| |' ...
    '|      ||    ||    ||      |' ...
    '| |||||||||| || |||||||||| |' ...
    '| |||||||||| || |||||||||| |' ...
    '|                          |' ...
    '||||||||||||||||||||||||||||' ...
    '____________________________' ...
    '____________________________'];


load('map_v10_regions.mat');
number_of_dots_per_region13 = floor(dot_percentage * length(region1));
number_of_dots_per_region24 = floor(dot_percentage * length(region2));
fruits = ['A' ; 'O' ; 'M' ; 'C' ; 'S'];
% dots, energizers, fruit region
dots1 = datasample(region1,number_of_dots_per_region13,'Replace',false);
ener1 = datasample(dots1, 1);
dots2 = datasample(region2,number_of_dots_per_region24,'Replace',false);
ener2 = datasample(dots2, 1);
dots3 = datasample(region3,number_of_dots_per_region13,'Replace',false);
ener3 = datasample(dots3, 1);
dots4 = datasample(region4,number_of_dots_per_region24,'Replace',false);
ener4 = datasample(dots4, 1);
dots_region = [dots1',dots2',dots3',dots4'];
energizer_region = [ener1, ener2, ener3, ener4];
fruit_region = setdiff(dots_region, energizer_region);

% check region
if length(unique(dots_region)) ~= length(dots_region)
    error('the dots region has replicated one')
end

if length(union(fruit_region, energizer_region)) ~= length(dots_region)
    error('fruit and energizer region has replication')
end
    
% fruit position
fruit_pos = IndexToPosition(datasample(fruit_region,1));
ener_pos = IndexToPosition(energizer_region);
while abs(fruit_pos(1) - ener_pos(1)) + abs(fruit_pos(2) - ener_pos(5)) < 6 ...
        || abs(fruit_pos(1) - ener_pos(2)) + abs(fruit_pos(2) - ener_pos(6)) < 6 ...
        || abs(fruit_pos(1) - ener_pos(3)) + abs(fruit_pos(2) - ener_pos(7)) < 6 ...
        || abs(fruit_pos(1) - ener_pos(4)) + abs(fruit_pos(2) - ener_pos(8)) < 6 ...
        || abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) < 4 % far away from pacman start point
    fruit_pos = IndexToPosition(datasample(fruit_region,1));
end
fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));
% creat map
empty_map(setdiff([dots_region,energizer_region],fruit_region)) = '.';
empty_map(energizer_region) = 'o';
empty_map(fruit_region) = datasample(fruits,1);

end

% empty_map = [ ...
%     '____________________________' ...
%     '____________________________' ...
%     '____________________________' ...
%     '||||||||||||||||||||||||||||' ...
%     '|111111111111||333333333333|' ...
%     '|1||||1|||||1||3|||||3||||3|' ...
%     '|1||||1|||||1||3|||||3||||3|' ...
%     '|1||||1|||||1||3|||||3||||3|' ...
%     '|11111111111113333333333333|' ...
%     '|1||||1||1||||||||3||3||||3|' ...
%     '|1||||1||1||||||||3||3||||3|' ...
%     '|111111||1111||3333||333333|' ...
%     '||||||1|||||1||3|||||3||||||' ...
%     '_____|1|||||1||3|||||3|_____' ...
%     '_____|1||          ||3|_____' ...
%     '_____|1|| |||--||| ||3|_____' ...
%     '||||||1|| |______| ||3||||||' ...
%     '5555555   |______|   5555555' ...
%     '||||||2|| |______| ||4||||||' ...
%     '_____|2|| |||||||| ||4|_____' ...
%     '_____|2||          ||4|_____' ...
%     '_____|2||2||||||||4||4|_____' ...
%     '||||||2||2||||||||4||4||||||' ...
%     '|222222222222||444444444444|' ...
%     '|2||||2||||| || |||||4||||4|' ...
%     '|2||||2||||| || |||||4||||4|' ...
%     '|2||||2              4||||4|' ...
%     '|2||||2|| |||||||| ||4||||4|' ...
%     '|2||||2||2||||||||4||4||||4|' ...
%     '|222222||2222||4444||444444|' ...
%     '|2||||||||||2||4||||||||||4|' ...
%     '|2||||||||||2||4||||||||||4|' ...
%     '|22222222222224444444444444|' ...
%     '||||||||||||||||||||||||||||' ...
%     '____________________________' ...
%     '____________________________'];
% for i = 1: 200
% fruit_pos = IndexToPosition(datasample(find(empty_map == '2'),1));
% while abs(fruit_pos(1) - 14) + abs(fruit_pos(2) - 27) >= 5 % far away from pacman start point
% fruit_pos = IndexToPosition(datasample(find(empty_map == '2'),1));
% fruit_region = PositionToIndex(fruit_pos(1),fruit_pos(2));
% empty_map(fruit_region) = '0';
% end
% empty_map(fruit_region) = '2';
% end
% GetMapAtFrame(empty_map)
