function initSquare1ghoasttTrial(continueTrial)

globalDefinitions;
global doesGhostMove;doesGhostMove = 0;
ghostActive=0;
ghostNumber = 1;
startTile = [14; 11];
if (continueTrial ==0) % start a new trial
    % initialize gameMap
    constructMap(28,36, [ ...
%         '____________________________' ...
%         '____________________________' ...
%         '____________________________' ...
%         '||||||||||||||||||||||||||||' ...
%         '|..........................|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|..........      ..........|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.                        .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|.           .            .|' ...
%         '|..........................|' ...
%         '||||||||||||||||||||||||||||' ...
%         '____________________________' ...
%         '____________________________' ...
%         '____________________________']);
        '____________________________' ...
        '____________________________' ...
        '____________________________' ...
        '||||||||||||||||||||||||||||' ...
        '|        ..........   .....|' ...
        '| ||||| |||||||||||| |||||.|' ...
        '| |   | |          |     | |' ...
        '| |        |||| |||||||  | |' ...
        '| |   ...  |||| |||||||  | |' ...
        '| |   ...                | |' ...
        '| |   ...                | |' ...
        '| ||||||||||       ...   | |' ...
        '|          |       ...   | |' ...
        '| ||||||||||       ...   | |' ...
        '| |                      | |' ...
        '| |              | |     | |' ...
        '| |||||||||||||||| ||||||| |' ...
        '|.     .      .   .       .|' ...
        '|.    |||||  ||  |||||    .|' ...
        '|.       .   .      .     .|' ...
        '| ||||||| |||||||||||||||| |' ...
        '| |     | |              | |' ...
        '| |                      | |' ...
        '| |   ...       |||||||||| |' ...
        '| |   ...       |          |' ...
        '| |   ...       |||||||||| |' ...
        '| |                ...   | |' ...
        '| |                ...   | |' ...
        '| |  ||||||| ||||  ...   | |' ...
        '| |  ||||||| ||||        | |' ...
        '| |     |          | |   | |' ...
        '|.||||| |||||||||||| ||||| |' ...
        '|.....   ..........        |' ...
        '||||||||||||||||||||||||||||' ...
        '____________________________' ...
        '____________________________' ...
        '____________________________']);
    
    
    % pacman settings
    pacMan.color = [1 1 0 0.8];
    % % % %         pacMan.frame = 0;
    pacMan.flipPerTile = tileSize / flipInterval;
    pacMan.step = 0;
    pacMan.numSteps = 10;
    pacMan.angle = 300;
    pacMan.frames = 0;
    pacMan.eatPauseFramesLeft = 0;
    pacMan.tile = struct('x',14,'y',18);
    pacMan.pixel = struct('x',(pacMan.tile.x)*tileSize,'y',(pacMan.tile.y-1)*tileSize+midTile.y);
    pacMan.dirEnum = -1;
    pacMan.nextDirEnum = -1;
    pacMan.dir = setDirFromEnum(-1);
    % 11.16
    pacMan.distToMid = struct('x', 0, 'y', 10);
    pacMan.tilePixel = struct('x', -1, 'y', -1);
    
    % ghost settings
    
    
    ghost = struct( ...
        'id', 1, ...
        'dir', struct('x',1,'y',0), ...
        'dirEnum', 0, ...
        'mode', 0, ...
        'targeting', 0, ...
        'scared', 0, ...
        'sigReverse', 0, ...
        'sigLeaveHome', 0, ...
        'faceDirEnum', 0, ...
        'pixel', struct('x',0,'y',0), ...        % pixel position
        'tile', struct('x',18,'y',17), ...       % tile position
        'tilePixel', struct('x',0,'y',0), ...    % pixel location inside tile
        'distToMid', struct('x',0,'y',0), ...    % pixel distance to mid-tile
        'targetTile', struct('x',0,'y',0), ...   % tile position used for targeting
        'frames', 0);    % frame count
    
    ghosts = [ghost ghost ghost ghost];
    %% 
   
    for g=1:ghostNumber
        ghosts(g).id = g;
        ghosts(g).mode = GHOST_PACING_HOME ;
        %ghosts(g).arriveHomeMode = startMode(g);
        ghosts(g).color = GHOST_COLOR{g};
        ghosts(g).tile.x = 13+g;
        ghosts(g).pixel.x = (startTile(1,g)-1)*tileSize + midTile.x;
        ghosts(g).pixel.y = (startTile(2,g)-1)*tileSize + midTile.y;
        ghosts(g).startPixel = ghosts(g).pixel;
        ghosts(g).dirEnum = mod(g,2)*2; % up or down
        ghosts(g).dir = setDirFromEnum(ghosts(g).dirEnum);
        ghosts(g).faceDirEnum = ghosts(g).dirEnum;
    end
    
   
    energizerInit;
    fruitInit;
else % continue a trial after PacMan is dead
    % pacman settings
    pacMan.tile = struct('x',14,'y',18);
    pacMan.pixel = struct('x',(pacMan.tile.x)*tileSize,'y',(pacMan.tile.y-1)*tileSize+midTile.y);
    pacMan.dirEnum = -1;
    pacMan.nextDirEnum = -1;
    pacMan.dir = setDirFromEnum(-1);

   %%
    % ghost settings
    for g=1:ghostNumber
        ghosts(g).id = g;
        ghosts(g).mode = GHOST_PACING_HOME  ;  %%  hy 1118 
        %ghosts(g).arriveHomeMode = startMode(g);
        ghosts(g).color = GHOST_COLOR{g};
        ghosts(g).tile.x = 13+g;
        ghosts(g).pixel.x = (startTile(1,g)-1)*tileSize + midTile.x;
        ghosts(g).pixel.y = (startTile(2,g)-1)*tileSize + midTile.y;
        ghosts(g).startPixel = ghosts(g).pixel;
        ghosts(g).dirEnum = mod(g,2)*2; % up or down
        ghosts(g).dir = setDirFromEnum(ghosts(g).dirEnum);
        ghosts(g).faceDirEnum = ghosts(g).dirEnum;
    end
    energizerInit;
    fruitInit;
end

end